FROM osrf/ros:humble-desktop-full-jammy

WORKDIR dev_ws/src
RUN git clone https://github.com/JACart2/ai-navigation.git
WORKDIR dev_ws
# RUN chmod +x src/ai-navigation/motor_control/resource/docker_startup_script.sh \
#    && ./src/ai-navigation/motor_control/resource/docker_startup_script.sh 




